import type { GraduateJobPost, JobPost } from '../types';

export const MOCK_CRAWLED_JOBS: JobPost[] = [
  {
    id: 1,
    companyName: '들어가고 싶은 회사',
    region: '경기',
    careerType: 'NEW_GRADUATE',
    jobType: 'BACKEND',
    fullLocation: '경기 성남시',
    deadline: '2026-06-30',
    detailUrl: 'https://www.saramin.co.kr',
    preferredLanguages: ['JAVA', 'SPRING'],
    isNew: true,
  },
  {
    id: 2,
    companyName: '네카라쿠배',
    region: '서울',
    careerType: 'JUNIOR',
    jobType: 'FRONTEND',
    fullLocation: '서울 강남구',
    deadline: '2026-07-15',
    detailUrl: 'https://www.wanted.co.kr',
    preferredLanguages: ['TYPESCRIPT', 'REACT', 'NEXT_JS'],
    isNew: true,
  },
  {
    id: 3,
    companyName: '데이터 분석 기업',
    region: '인천',
    careerType: 'SENIOR',
    jobType: 'DATA',
    fullLocation: '인천 연수구',
    deadline: '2026-06-20',
    detailUrl: 'https://www.jobkorea.co.kr',
    preferredLanguages: ['PYTHON', 'MYSQL'],
    isNew: true,
  },
  {
    id: 4,
    companyName: '좋은 스타트업',
    region: '부산',
    careerType: 'ANY',
    jobType: 'BACKEND',
    fullLocation: '부산 해운대구',
    deadline: '2026-08-01',
    detailUrl: 'https://www.jumpit.co.kr',
    preferredLanguages: ['JAVA', 'SPRING', 'MYSQL'],
  },
  {
    id: 5,
    companyName: '대기업 IT',
    region: '서울',
    careerType: 'NEW_GRADUATE',
    jobType: 'FULLSTACK',
    fullLocation: '서울 중구',
    deadline: '2026-06-10',
    detailUrl: 'https://www.linkedin.com',
    preferredLanguages: ['JAVASCRIPT', 'NODEJS', 'REACT'],
  },
];

export const MOCK_GRADUATE_JOBS: GraduateJobPost[] = [
  {
    id: 101,
    companyName: '들어가고 싶은 회사',
    region: '경기',
    careerType: 'NEW_GRADUATE',
    jobType: 'BACKEND',
    fullLocation: '경기 성남시',
    deadline: '2026-06-30',
    detailUrl: 'https://www.saramin.co.kr',
    preferredLanguages: ['JAVA', 'SPRING'],
    isNew: true,
    graduateMemberId: 1,
    graduateNickname: '선배님',
    graduateDepartment: '컴퓨터공학과',
    graduateJobType: 'BACKEND',
    graduateCareerYear: 3,
  },
  {
    id: 102,
    companyName: '좋은 IT 기업',
    region: '서울',
    careerType: 'JUNIOR',
    jobType: 'FRONTEND',
    fullLocation: '서울 마포구',
    deadline: '2026-07-20',
    detailUrl: 'https://www.wanted.co.kr',
    preferredLanguages: ['TYPESCRIPT', 'REACT'],
    graduateMemberId: 2,
    graduateNickname: '멘토선배',
    graduateDepartment: '소프트웨어학과',
    graduateJobType: 'FRONTEND',
    graduateCareerYear: 5,
  },
];
